Added contributors list through the git hub api
fossasia/gci17.fossasia.org pull request #118
Opened 2017-12-04 20:05 UTC by STEdirisuriya

Added contributors list through the git hub API. for my GCI - task Website: Add and Enhance the "Contributors Section" for the FOSSASIA GCI site by using the Github API ( FOSSASIA ). Please check this. 
https://stedirisuriya.github.io/gci17.fossasia.org/

2017-12-05 04:22 UTC, duttaditya18 commented
Squash the commits and resolve the conflicts. Then ping the fossasia/fossasia-gci team.

2017-12-05 06:59 UTC, isuruAb commented
@STEdirisuriya  please resolve this conflict. then we can merge this.

2017-12-05 13:37 UTC, STEdirisuriya commented
OK I resolved all conflicts...

2017-12-05 15:12 UTC, abishekvashok commented
@STEdirisuriya again you got conflicts

2017-12-05 15:50 UTC, akshatnitd commented
Please resolve the conflicts. I cannot review before all the conflicts are resolved

2017-12-05 17:37 UTC, STEdirisuriya commented
OK. review please

2017-12-05 18:28 UTC, isuruAb approved these changes

2017-12-05 18:34 UTC, ParthS007 commented
![image](https://user-images.githubusercontent.com/24358501/33623976-d07d5238-da18-11e7-9174-dbe85d8e6228.png)
![image](https://user-images.githubusercontent.com/24358501/33623996-e4ab700a-da18-11e7-8716-8d29611b9aa6.png)

2017-12-05 18:35 UTC, ParthS007 requested changes
![image](https://user-images.githubusercontent.com/24358501/33624039-141c1fb0-da19-11e7-9401-ba5b3b852899.png)
![image](https://user-images.githubusercontent.com/24358501/33624052-1cfccee0-da19-11e7-9c6c-f3d38628f685.png)

2017-12-05 18:36 UTC, ParthS007 commented
@STEdirisuriya Why Mentors and Students are not visible in preview link?

2017-12-05 18:41 UTC, invinciblycool commented
@ParthS007 those template tags are rendered during deployment . Please check.

2017-12-05 18:43 UTC, isuruAb reviewed
please check the mentors section

2017-12-05 19:42 UTC, chashmeetsingh requested changes
Please resolve the merge issues.

2017-12-05 19:42 UTC, chashmeetsingh commented on index.html
> +<<<<<<< HEAD
Please fix the merge conflict. There are many places this needs to be fixed, please take a look.

Thanks!

2017-12-05 20:40 UTC, STEdirisuriya commented
I finished making web site. no error there now
![errfix](https://user-images.githubusercontent.com/33794760/33629575-8e979ad8-da2a-11e7-8c3d-38e4f961e039.PNG)
![errfix2](https://user-images.githubusercontent.com/33794760/33629581-92d1f51c-da2a-11e7-9670-93196b26c3c8.PNG)

2017-12-05 20:54 UTC, merged

2017-12-05 20:55 UTC, invinciblycool commented
Thanks @STEdirisuriya

2017-12-05 21:05 UTC, STEdirisuriya commented
please approve my review please

2017-12-05 21:05 UTC, supunTE commented
@invinciblycool

2017-12-05 21:11 UTC, ParthS007 commented
![image](https://user-images.githubusercontent.com/24358501/33630899-f27007b2-da2e-11e7-8fe4-2217ed981100.png)

2017-12-05 21:16 UTC, ParthS007 commented
@invinciblycool Please see the screenshot and If contributors have four columns then Students and Mentors should also have 4 columns as Uniformity is necessary. I hope that you now understand what I am trying to say

2017-12-05 21:17 UTC, STEdirisuriya commented
oh yes

2017-12-05 21:18 UTC, invinciblycool commented
Yes, I do understand but the student has enhanced the contributors section
using github api. And that is a design issue which can be improved upon by
opening issues and continued contribution.

On 06-Dec-2017 2:46 AM, "Parth" <notifications@github.com> wrote:

> @invinciblycool <https://github.com/invinciblycool> Please see the
> screenshot and If contributors have four columns then Students and Mentors
> should also have 4 columns as Uniformity is necessary. I hope that you now
> understand what I am trying to say
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/118#issuecomment-349444043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXjEVTgGIcsAb4NfqKjMH0dZJxxjVYuWks5s9bK0gaJpZM4Q1O8C>
> .
>

2017-12-05 21:24 UTC, ParthS007 commented
ok @invinciblycool :+1: , its ok but there is empty space in contributors section itself.

2017-12-06 04:31 UTC, STEdirisuriya commented
That is your browser's version problem. Look at those screen shots. 
![noerr](https://user-images.githubusercontent.com/33794760/33631383-683a7d32-da30-11e7-9d0f-f6cbfc9db45b.PNG)
![noerr2](https://user-images.githubusercontent.com/33794760/33631384-688677a0-da30-11e7-90df-8bdbe4f18cbd.PNG)
![noerr3](https://user-images.githubusercontent.com/33794760/33631385-68bd01d0-da30-11e7-8953-011067607d42.PNG)
![noerr4](https://user-images.githubusercontent.com/33794760/33631386-68f82864-da30-11e7-9ce3-37b442d16572.PNG)