minor corrections
fossasia/gci17.fossasia.org pull request #124
Opened 2017-12-05 11:19 UTC by VibhorCodecianGupta

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-05 11:25 UTC, akshatnitd requested changes
Correct the typo of Linkedin

2017-12-05 11:40 UTC, abishekvashok approved these changes

2017-12-05 18:05 UTC, ba11b0y requested changes

2017-12-05 18:05 UTC, invinciblycool commented on README.md
>    Linkedin: Mentor's Linkein Page
Please correct the typo

2017-12-12 05:10 UTC, anshumanv requested changes
Conflicts

2017-12-12 06:31 UTC, ParthS007 commented
@VibhorCodecianGupta  Please resolve conflicts and your PR is ready to merge !

2017-12-14 16:05 UTC, isuruAb reviewed
@VibhorCodecianGupta  please resolve conflicts

2017-12-15 11:29 UTC, VibhorCodecianGupta commented
Hello! Apologies for the extremely late reply. I have resolved the existing conflicts, and I think that this must be it. Please review :D

2017-12-15 11:31 UTC, ParthS007 approved these changes

2017-12-15 11:31 UTC, merged