Update students.yml
fossasia/gci17.fossasia.org pull request #129
Opened 2017-12-05 15:05 UTC by FreakinBabaJi

Updated the studentss list 
Name: Prasenjit Gautam

2017-12-05 15:12 UTC, abishekvashok requested changes
Also add your image.

2017-12-05 15:12 UTC, abishekvashok commented on _data/students.yml
> -  github: Jerry2001
Please don't remove an existing student.

2017-12-05 15:23 UTC, FreakinBabaJi commented
I'm facing problem in uploading the image
On Dec 5, 2017 8:42 PM, "Abishek V Ashok" <notifications@github.com> wrote:

> *@abishekvashok* requested changes on this pull request.
>
> Also add your image.
> ------------------------------
>
> In _data/students.yml
> <https://github.com/fossasia/gci17.fossasia.org/pull/129#discussion_r154974591>
> :
>
> > @@ -78,7 +78,9 @@
>    lat: 28.641485
>    lng: 77.371386
>
> -- name: Ngô Hồng Phúc
> -  image: oem.jpg
> -  github: Jerry2001
>
> Please don't remove an existing student.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/129#pullrequestreview-81216481>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYMV4zp8Q6msozzkvguIn7kMNZP_ANvnks5s9V1QgaJpZM4Q2b06>
> .
>

2017-12-05 15:25 UTC, akshatnitd commented
@FreakinBabaJi I can see that you have not added the photo before pushing. Make sure to ```git add <photo-path>``` before pushing. Also, do not remove any existing student.

2017-12-05 16:32 UTC, invinciblycool commented
@FreakinBabaJi Please do not remove the existing student, it is causing a merge conflict. Please add yourself without removing anyone else.

2017-12-05 16:35 UTC, FreakinBabaJi commented
I'm not removing any existing student . I'm simply adding my name but I
don't know why this conflict is showing up
On Dec 5, 2017 10:02 PM, "Rahul Tiwari" <notifications@github.com> wrote:

> @FreakinBabaJi <https://github.com/freakinbabaji> Please do not remove
> the existing student, it is causing a merge conflict. Please add yourself
> without removing anyone else.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/129#issuecomment-349360201>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYMV4xTyHa1TNprFK6VzZxnso6qVtCWcks5s9XAYgaJpZM4Q2b06>
> .
>

2017-12-05 16:39 UTC, invinciblycool commented
Please check your students.yml in your fork here https://github.com/FreakinBabaJi/gci17.fossasia.org/blob/patch-1/_data/students.yml
It shows that you have removed an existing student.
Don't worry, just edit again and make a commit.
Good going

2017-12-05 16:42 UTC, ba11b0y requested changes
Please make the changes

2017-12-06 11:53 UTC, abishekvashok commented
Conflicts, pls resolve them

2017-12-06 11:57 UTC, FreakinBabaJi commented
I'm unable to get what conflicts are actually there? Please help me
On Dec 6, 2017 5:23 PM, "Abishek V Ashok" <notifications@github.com> wrote:

> Conflicts, pls resolve them
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/129#issuecomment-349617634>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYMV477FFSmsPcgWENKlABlPW14U57dGks5s9oBVgaJpZM4Q2b06>
> .
>

2017-12-06 12:08 UTC, abishekvashok commented
@FreakinBabaJi sure, conflicts arise when yourchanges giff was overwritten by a recent commit. So you ome into a conflict. You have a conflict in _data/students.yml. To resolve conflicts pls follow this guide:
http://tedfelix.com/software/git-conflict-resolution.html
http://genomewiki.ucsc.edu/index.php/Resolving_merge_conflicts_in_Git

2017-12-06 12:29 UTC, closed without merging