Fixed merge conflict, added student entry etc.
fossasia/gci17.fossasia.org pull request #138
Opened 2017-12-06 08:25 UTC by 2coolife

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

# Requirements

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Fixed the merge conflict as mentioned in #136 
- Added back Jekyll #136 
- Resized all student images to 240x240 px
- Did some improvements and fixes in design
- Did some minor tweaks and cleaup

2017-12-06 08:48 UTC, duttaditya18 commented
Merge the commits please!

2017-12-06 10:11 UTC, isuruAb commented
@2coolife could you please squash all these commits.
please follow this video tutorial to learn about squashing
https://www.youtube.com/watch?v=vp7-NeURmFg&t=35s

2017-12-06 11:54 UTC, abishekvashok commented
@2coolife  pls properly rebase your changes. I think you have made commits instead of a single merge commit.

2017-12-06 13:05 UTC, 2coolife commented
ok now

2017-12-06 13:16 UTC, ba11b0y requested changes

2017-12-06 13:16 UTC, invinciblycool commented on _data/mentors.yml
> +- name: Rahul Tyagi
My name is Rahul Tiwari and twitter handle is invinciblycool
Please make the changes

2017-12-06 13:19 UTC, invinciblycool commented
@2coolife Actually I had overlooked some recent commits and merged it, which was the cause of the issue.
Thanks very much for resolving the issue. Please make the requested changes and wait for review.

2017-12-06 13:31 UTC, 2coolife commented
Did the changes but mentors.yml is getting a merge conflict now. : /

2017-12-07 16:41 UTC, anshumanv approved these changes

2017-12-07 16:52 UTC, merged

2017-12-07 16:52 UTC, anshumanv commented
Thanks @2coolife :smile: