Task
fossasia/gci17.fossasia.org pull request #194
Opened 2017-12-09 02:53 UTC by HasaluSL

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-09 04:42 UTC, abishekvashok requested changes

2017-12-09 04:42 UTC, abishekvashok commented on Interview a Student participating in the Contest
> +https://introductorymusicblockstutorial.wordpress.com/
Pls don't add this.

2017-12-09 04:42 UTC, abishekvashok commented on index.html
> +						<a href="https://twitter.com/@{{cyberdoc.twitter}}" class="icon-a">
Add yourself to _data/students.yml and not here. Pls see the readme.md

2017-12-09 04:42 UTC, abishekvashok commented on index.html
> +								<div class="title mb16">
Add this to blogs.yml see the readme

2017-12-11 12:17 UTC, anshumanv commented
Duplicate of #258

2017-12-12 01:33 UTC, isuruAb reviewed
@HasaluSL  please describe what you have changed and why. cheers 👍

2017-12-12 06:21 UTC, ParthS007 commented
Closing this as a duplicate of #259

2017-12-12 06:21 UTC, closed without merging