Added Blog image and information
fossasia/gci17.fossasia.org pull request #201
Opened 2017-12-09 07:20 UTC by FreakinBabaJi

Blog title: root to Open-Source with FOSSASIA
img: gutter.jpg

2017-12-09 07:45 UTC, akshatnitd requested changes
You have added the image twice. Remove the unneccesary one and also try to squash the commits

2017-12-09 19:17 UTC, akshatnitd commented
@FreakinBabaJi Great work! Now squash the commits, so that I can go ahead and merge the PR.

2017-12-10 06:21 UTC, CloudyPadmal commented on _data/blogs.yml
> +  img: gutter.jpg
Change this to `rsz_gutter.jpg` as it is the file name :)

2017-12-10 06:24 UTC, DotSlashTX reviewed
named the image as it was in img/blog

2017-12-10 06:43 UTC, akshatnitd commented
@FreakinBabaJi Please resolve the conflicts and squash the commits properly

2017-12-10 07:00 UTC, FreakinBabaJi commented
resolved all conflicts :)

2017-12-10 07:04 UTC, ParthS007 approved these changes
LGTM ! Good work , If you can squash commits it would be a plus 👍

2017-12-10 07:05 UTC, ParthS007 commented
@FreakinBabaJi , You can go through this https://gist.github.com/patik/b8a9dc5cd356f9f6f980 for squash ing of commits.

2017-12-10 07:36 UTC, ParthS007 commented
@FreakinBabaJi  I am merging this PR ,Try to squash commits from next PR 👍

2017-12-10 07:36 UTC, merged