Added Blog (Interview)
fossasia/gci17.fossasia.org pull request #245
Opened 2017-12-10 15:11 UTC by saarthakchats

Interview with Samyak and Vatsal -- Two Open Source contributors.

2017-12-10 15:17 UTC, abishekvashok commented
Pls make sure the image is 240x240 px

2017-12-10 15:20 UTC, saarthakchats commented
@abishekvashok 
Is it fine now?

2017-12-10 15:22 UTC, saarthakchats commented
Sorry for closing it (by mistake).

2017-12-10 15:23 UTC, vaibhavsingh97 requested changes

2017-12-10 15:23 UTC, vaibhavsingh97 commented on _data/blogs.yml
> +  img: suups.png
Can you please rename the pic to `10.png`.

2017-12-10 15:26 UTC, saarthakchats commented
@vaibhavsingh97 
Done

2017-12-10 15:26 UTC, abishekvashok commented
Lets wait for Travis.

2017-12-10 15:30 UTC, vaibhavsingh97 commented
@saarthakchats Please share deployment link.

2017-12-10 16:09 UTC, saarthakchats commented
https://heuristic-volhard-32af86.netlify.com/

I am still not sure how to release deployment link

2017-12-10 16:16 UTC, kubami9 commented
@saarthakchats you can do it by setting GitHub pages in your forked repository options 😃

2017-12-10 16:18 UTC, saarthakchats commented
@kubami9 
I still don't understand how

2017-12-10 16:54 UTC, kubami9 commented
@saarthakchats you can go to your repo options and after scrolling down a little bit you have GitHub pages options, you gotta make sure it's enabled and give us the link :)

2017-12-11 14:45 UTC, saarthakchats commented
https://saarthakchats.github.io/deployed-gungci17.fossasia.org/

2017-12-11 14:46 UTC, anshumanv approved these changes

2017-12-11 14:46 UTC, anshumanv commented
Please resolve conflicts and this should be okay.

2017-12-11 14:47 UTC, anshumanv commented on _data/blogs.yml
> +
Remove this extra line please.

2017-12-11 14:48 UTC, saarthakchats commented
@anshumanv 
I think its fine now

2017-12-11 14:49 UTC, saarthakchats commented
@anshumanv 
Removed the line

2017-12-11 14:54 UTC, merged