Added Photo and Blog
fossasia/gci17.fossasia.org pull request #248
Opened 2017-12-10 16:22 UTC by samyakbvs

2017-12-10 17:21 UTC, gabru-md commented
Please give us a link to your changes.

2017-12-10 17:22 UTC, samyakbvs commented
What do you mean?

2017-12-10 17:22 UTC, samyakbvs commented
What do you mean?
@gabru-md

2017-12-10 17:48 UTC, samyakbvs commented
Please can we go ahead without a test link
Just a request :)

2017-12-10 17:50 UTC, anshumanv commented
Hey @samyakbvs there have been a lot of PRs from you and none of them had a test link, please provide us a test link so we can verify the changes quickly from now on. I hope you understand and take this in a positive way.

2017-12-10 17:51 UTC, STEdirisuriya commented
Give a link for see changes

2017-12-10 17:55 UTC, samyakbvs commented
OKay but please explain to me how to do it

2017-12-10 17:55 UTC, samyakbvs commented
@anshumanv

2017-12-10 17:58 UTC, anshumanv commented
Follow - https://pages.github.com/

2017-12-10 18:12 UTC, samyakbvs commented
@anshumanv I have gone through that page several times but I could find nothing so can you pls explain to me how its done

2017-12-10 18:16 UTC, anshumanv commented
It's simple read and follow - https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

Please tell me which line is difficult to understand. :smile:

2017-12-10 18:17 UTC, anshumanv commented
![image](https://user-images.githubusercontent.com/21009455/33807951-836277b8-de04-11e7-98e0-731dbd389ac4.png)

2017-12-10 18:17 UTC, anshumanv commented
![image](https://user-images.githubusercontent.com/21009455/33807953-8a1bf368-de04-11e7-95fb-466bf29904dc.png)

2017-12-10 18:18 UTC, anshumanv commented
![image](https://user-images.githubusercontent.com/21009455/33807954-928bf318-de04-11e7-9aaa-55c5c495d28b.png)

2017-12-10 18:23 UTC, samyakbvs commented
https://samyakbvs.github.io/gci17.fossasia.org/
Is this the one?

2017-12-10 18:24 UTC, anshumanv commented
Yes, exactly. See I told you it's easy and you were worried about it for no reason. :smile:

2017-12-10 18:26 UTC, samyakbvs commented
Thank you so much

2017-12-10 18:26 UTC, samyakbvs commented
now can the PR merge?

2017-12-10 18:27 UTC, samyakbvs commented
@anshumanv

2017-12-10 18:29 UTC, anshumanv commented
No, Let others review, provide feedback, they will merge when they feel apt.
Also, we're unsure if we need the interview in this form so please wait for a while.

2017-12-10 18:30 UTC, samyakbvs commented
Okay no problem

2017-12-10 18:35 UTC, samyakbvs commented
Till then should I abandon the task and work on another one

2017-12-10 18:36 UTC, samyakbvs commented
Roughly how much time will it take for more people to review?

2017-12-10 18:38 UTC, samyakbvs commented
@anshumanv

2017-12-10 18:51 UTC, anshumanv commented
From my understanding, since the task says either a video or a blog, I think this should work.

2017-12-10 18:52 UTC, anshumanv requested changes

2017-12-10 18:52 UTC, anshumanv commented on _config.yml
> +theme: jekyll-theme-cayman
Remove this file

2017-12-10 19:41 UTC, samyakbvs commented
Done!

2017-12-10 19:43 UTC, samyakbvs commented
@anshumanv

2017-12-11 02:01 UTC, abishekvashok approved these changes
LGTM, but if you could squash the commits, it will be better.

2017-12-11 05:34 UTC, akshatnitd requested changes
The demo link you provided isn't working. Can you please check it.

Also, please squash the commits. Refer https://gist.github.com/patik/b8a9dc5cd356f9f6f980 for help.

2017-12-11 06:45 UTC, samyakbvs commented
https://samyakbvs.github.io/gci17.fossasia.org/

2017-12-11 06:46 UTC, samyakbvs commented
The link is working perfectly fine now

2017-12-11 07:06 UTC, samyakbvs commented
@anshumanv  Please excuse me for the last time, I will squash the commits next time positively. I am not able to do them now as I didn't work on Github desktop

2017-12-11 07:06 UTC, samyakbvs commented
next time for sure you will see squashed commits

2017-12-11 07:07 UTC, samyakbvs commented
I hope you understand :)

2017-12-11 07:14 UTC, anshumanv commented
Okay, no issues about squashing commits if you cant do it this time. 
Please wait for others to review.

2017-12-11 13:01 UTC, ParthS007 approved these changes
LGTM !

2017-12-11 13:04 UTC, anshumanv approved these changes

2017-12-11 13:04 UTC, anshumanv commented
@ParthS007 should we merge or wait?

2017-12-11 13:07 UTC, ParthS007 commented
I think we should wait for @akshatnitd  approval.

2017-12-11 13:10 UTC, anshumanv commented
Aight, cool. Let's wait for him to complete review.

2017-12-11 15:12 UTC, samyakbvs commented
@akshatnitd  Please see if it is fine now?

2017-12-11 16:07 UTC, abishekvashok commented
@samyakbvs can you squash rest looks fine.

2017-12-11 16:10 UTC, harshit98 commented
@samyakbvs I have observed you many times, you don't keep patience.

> Roughly how much time will it take for more people to review?

Mentors will review your work as soon as they will get time.  You should respect their time as well.

Since a lot of pull request of yours has been merged, I think it's time you should learn squashing of commits here. Keep up the good work! 💯 

@abishekvashok @anshumanv @ParthS007 Please help him out. Thanks!

2017-12-11 16:20 UTC, samyakbvs commented
Sorry, @harshit98 will take care of that from next time and now I know that how to squash commits but I have done my work directly on the site so I am not able to squash the commits, that's why I am saying that Pls excuse me for the last time. Also, I am sorry again

2017-12-11 16:23 UTC, harshit98 commented
Okay @samyakbvs. Next time, please squash your commits. I'm merging this pull request. 👍

2017-12-11 16:23 UTC, samyakbvs commented
Thanks

2017-12-11 16:23 UTC, merged