Aligned
fossasia/gci17.fossasia.org pull request #280
Opened 2017-12-12 16:40 UTC by samyakbvs

#275

fixed

2017-12-12 16:40 UTC, samyakbvs commented
Sorry for closing the last PR @anshumanv

2017-12-12 16:43 UTC, anshumanv commented
Test link?

2017-12-12 16:48 UTC, samyakbvs commented
one minute

2017-12-12 17:11 UTC, samyakbvs commented
https://samyakbvs.github.io/samyakjainbvs-gci17.fossasia.org/

2017-12-12 17:11 UTC, samyakbvs commented
Squashing commits please wait

2017-12-12 17:17 UTC, samyakbvs commented
Pls merge and also thank you so much @anshumanv and @abishekvashok for helping me in learning something new

2017-12-12 17:18 UTC, samyakbvs commented
💯

2017-12-12 17:28 UTC, samyakbvs commented
Wait I will be providing a new deployment link

2017-12-12 17:35 UTC, samyakbvs commented
https://samyakbvs.github.io/samyak-jain-gci17.fossasia.org/

2017-12-12 17:40 UTC, anshumanv commented
The image is still not properly scaled, it's shrunk now. Please try to make it into dimensions as other images.

2017-12-12 17:47 UTC, samyakbvs commented
Can you please approve like this as at least they are aligned and also only one picture is out of dimension the other one cant be noticed also I have checked everything I can't find anything that restricts their size
Please approve :) @anshumanv

2017-12-12 17:49 UTC, samyakbvs commented
To add on, the last image would look overstretched if it is expanded further so take that into consideration too

2017-12-12 17:49 UTC, samyakbvs commented
and the commits are finally squashed 👍

2017-12-12 17:51 UTC, anshumanv commented
Good going with that, but IMO this PR doesn't really solve the issue.
Please wait for other reviewers to review and see what they have to say.
Thanks

2017-12-13 07:22 UTC, ParthS007 requested changes

2017-12-13 07:22 UTC, ParthS007 commented on css/theme-red.css
> +  max-width: 100%
@samyakbvs  please add `;`.issue will be fixed

2017-12-13 12:23 UTC, samyakbvs commented
Done @ParthS007 and thanks

2017-12-13 12:23 UTC, samyakbvs commented
pls merge :)

2017-12-13 12:42 UTC, ParthS007 commented
@anshumanv Have a look, are you facing any Issues now?

2017-12-13 12:45 UTC, samyakbvs commented
Do i have to make a new test link or refresh the same @ParthS007

2017-12-13 12:46 UTC, abishekvashok requested changes
It seem to be broken in mobile.

2017-12-13 12:46 UTC, anshumanv commented
@ParthS007, the image in the last column is still off, should we merge? But then this won't be any substantial contribution(just some minor styling changes) and the task asks for substantial contribution.
![image](https://user-images.githubusercontent.com/21009455/33939518-885d0a06-e031-11e7-9c61-3892414da1c5.png)

2017-12-13 12:47 UTC, abishekvashok commented
![screenshot_2017-12-13-18-15-49-531_com android chrome](https://user-images.githubusercontent.com/8947010/33939605-d1f71378-e031-11e7-9c93-2c2c6400b977.png)

2017-12-13 12:53 UTC, ParthS007 commented
@anshumanv agreed with you , @samyakbvs you have done good job till now but please check responsiveness so that PR can be merged.

2017-12-13 12:54 UTC, ParthS007 requested changes

2017-12-13 12:54 UTC, ParthS007 commented on css/theme-red.css
> +    padding: 5px;   max-width: 240px;   max-height: 159px;   min-width: 32px;   min-height: 21px;
write every property in different line.

2017-12-13 13:09 UTC, samyakbvs commented
@anshumanv  when I opened the link it doesn't show that the last column is off
![screen shot 2017-12-13 at 6 36 42 pm](https://user-images.githubusercontent.com/34275800/33940393-c585c8e8-e034-11e7-95e7-fa44b9f0f8e6.png)

2017-12-13 13:12 UTC, samyakbvs commented
![screen shot 2017-12-13 at 6 41 16 pm](https://user-images.githubusercontent.com/34275800/33940515-45863992-e035-11e7-8064-42f1cf25593a.png)
Also the responsiveness is working fine on the laptop

2017-12-13 13:14 UTC, samyakbvs commented
I don't know why it isnt on phone @ParthS007

2017-12-13 13:44 UTC, samyakbvs commented
![screen shot 2017-12-13 at 7 13 23 pm](https://user-images.githubusercontent.com/34275800/33941782-c35b1d7a-e039-11e7-80d0-efdb486802d0.png)
Also someone pls tell me how to access the highlighted parts

2017-12-13 13:45 UTC, samyakbvs commented
@abishekvashok

2017-12-13 14:15 UTC, samyakbvs commented
I have added another commit I hope now my PR is substantial enough

2017-12-13 14:15 UTC, samyakbvs commented
@anshumanv

2017-12-13 14:22 UTC, anshumanv requested changes

2017-12-13 14:22 UTC, anshumanv commented on index.html
> +			<a class="btn-lg btn" href="http://foundry.mediumra.re/chooser.html">Explore Foundry</a>
What's the need for this?

2017-12-13 14:22 UTC, anshumanv commented on index.html
> +			<a class="btn-lg btn" href="http://foundry.mediumra.re/chooser.html">Explore Foundry</a>
and this?

2017-12-13 14:23 UTC, anshumanv commented
@samyakbvs number of commits isn't any criteria for substantial contribution.

2017-12-13 14:25 UTC, samyakbvs commented on index.html
> +			<a class="btn-lg btn" href="http://foundry.mediumra.re/chooser.html">Explore Foundry</a>
I just did because the links were empty

2017-12-13 14:25 UTC, samyakbvs commented on index.html
> +			<a class="btn-lg btn" href="http://foundry.mediumra.re/chooser.html">Explore Foundry</a>
same goes for this one

2017-12-13 14:26 UTC, samyakbvs commented
Okay @anshumanv, I will do something else too if you want...

2017-12-13 14:28 UTC, samyakbvs commented
@ParthS007 I hope now my PR is good to go?

2017-12-13 14:31 UTC, samyakbvs commented
@anshumanv it says explore foundry so I added the link to the foundry

2017-12-13 14:34 UTC, anshumanv commented
It's some base content from the template, nowhere related to FOSSASIA.

2017-12-13 14:39 UTC, samyakbvs commented
Oh so shall I remove it then?

2017-12-13 15:36 UTC, abishekvashok commented on index.html
> +		<a class="btn btn-filled btn-lg mb32 mt-xs-40" href="https://www.realestate.com.au/property/53-hopetoun-rd-toorak-vic-3142">Register Interest<a>
Why should you include this link?

2017-12-13 16:05 UTC, samyakbvs commented
Please don't close the PR

2017-12-13 16:40 UTC, samyakbvs commented
Please now see
@anshumanv @ParthS007

2017-12-13 18:27 UTC, anshumanv commented
Images are still messed up @samyakbvs 
![whatsapp image 2017-12-13 at 11 55 59 pm](https://user-images.githubusercontent.com/21009455/33955364-46880326-e061-11e7-8476-79b81ac0ff1e.jpeg)

2017-12-14 04:46 UTC, duttaditya18 commented
I don't think this is ever required. The current website looks good already.

2017-12-15 13:10 UTC, samyakbvs commented
How should I deal with it @anshumanv

2017-12-15 13:18 UTC, anshumanv commented
Experiment with styling and see what works, I think there's not much problem with the current setup.

2017-12-16 15:33 UTC, ParthS007 commented
@samyakbvs I agree with @anshumanv , Please close this PR and you can find other bugs and made PR solving them.Thanks 👍

2017-12-17 16:38 UTC, closed without merging