Update students.yml
fossasia/gci17.fossasia.org pull request #281
Opened 2017-12-12 16:53 UTC by lavavi

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-12 16:54 UTC, lavavi commented
![lavavi](https://user-images.githubusercontent.com/34159043/33897354-3465689a-df8b-11e7-8c81-083187b6d945.jpg)

2017-12-12 17:01 UTC, lavavi commented on _data/students.yml
> +  image: lavavi.jpg
![lavavi](https://user-images.githubusercontent.com/34159043/33897720-3b5d36f4-df8c-11e7-96ac-588eb8dbc629.jpg)

2017-12-12 17:46 UTC, anshumanv requested changes
Please add your image in this directory - `img/students`

2017-12-12 21:28 UTC, YashKumarVerma commented
@lavavi  please add the changes in the PR description too.

2017-12-13 01:55 UTC, isuruAb requested changes
hi @lavavi , please add a 240x240 sized image

2017-12-13 07:41 UTC, ParthS007 commented
@lavavi Please update your PR

2017-12-13 14:45 UTC, closed without merging