added installation_linux.md
fossasia/gci17.fossasia.org pull request #303
Opened 2017-12-13 21:21 UTC by Tanonic

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ x] Read and understood (see CONTRIBUTING.md)
- [ x] Included a live link or preview screenshot
- [ x] Images are `240 x 240` [w x h]
- [ x] Resolved merge conflicts
- [ x] Included a description of my change below

# Things done in this Pull Request

- Added documentation on how to setup the website locally, on linux. You can see it here https://github.com/Tanonic/gci17fossasia/blob/gh-pages/installation_linux.md

2017-12-14 04:19 UTC, rupav reviewed
@Tanonic, Please post a Screenshot of the browser which shows you were successful in setting up the local server.

2017-12-14 04:28 UTC, the-codingninja requested changes
Please attach screenshots also

2017-12-14 05:28 UTC, akshatnitd requested changes
Check inline comments

2017-12-14 05:28 UTC, akshatnitd commented on installation_linux.md
> +1. Open a Terminal and use a package manager to install ruby. For example, on Ubuntu or Debian use `sudo apt install ruby` or on Arch Linux `sudo pacman -S ruby`
It will be ```apt-get```

2017-12-14 05:28 UTC, akshatnitd commented on installation_linux.md
> +5. Now open Gemfile(with any text editor e.g. `sublime` or `nano`) and then Comment `gem 'github-pages', group: :jekyll_plugins` and uncomment `#gem 'jekyll-sitemap'`
Is this uncommenting thing required for Linux as well ? Can you please justify the reason

2017-12-14 18:00 UTC, Tanonic commented
I added a screenshot in the description and also fixed requested items earlier today @ms10398 @akshatnitd

2017-12-14 18:36 UTC, akshatnitd commented
LGTM :+1:

2017-12-14 18:36 UTC, akshatnitd approved these changes

2017-12-14 18:44 UTC, anshumanv commented
@Tanonic I think @ms10398 wants screenshots to be added with the documentation, so users can see how it looks like on successfully running it.
Please confirm @ms10398.

2017-12-14 19:15 UTC, Tanonic commented
@anshumanv could be, but the Windows documentation doesn't have any either.

2017-12-14 19:22 UTC, anshumanv commented
Yes, I agree @Tanonic, probably we can ask the one who added windows docs too!
Anyways please @ms10398 clarify where he needs screenshots.

2017-12-15 04:13 UTC, rupav approved these changes
😃Good Work and thanks for the screenshot provided.

2017-12-15 04:50 UTC, the-codingninja approved these changes
LGTM!!

2017-12-15 04:53 UTC, merged