Please update the following.
fossasia/gci17.fossasia.org pull request #314
Opened 2017-12-15 10:54 UTC by Mridulbirla13

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- A GCI- 2017 task
- Added the profile information in the Students.yml section.
- Added the image in the img/student section.
-The screenshot proof of my task is 
![screenshot](https://user-images.githubusercontent.com/24730417/34039054-3e5d6f2a-e1b4-11e7-99ed-6f158be99ded.PNG)

2017-12-15 10:59 UTC, ParthS007 requested changes
Please use Image of only `240 * 240 ` dimension

2017-12-15 12:08 UTC, isuruAb reviewed
please resize your image to 240x240

2017-12-15 13:08 UTC, the-codingninja requested changes
Please resize your image to fix travis

2017-12-16 05:40 UTC, abishekvashok commented
Please resolve the conflicts.

2017-12-16 11:03 UTC, akshatnitd requested changes
Make requested changes and resolve conflicts

2017-12-16 11:03 UTC, akshatnitd commented on _data/students.yml
> +  twitter: @mridulbirla13
Please remove the ```@```, as the travis build fails because of this.

2017-12-16 12:32 UTC, ParthS007 commented
closing this as a duplicate of #326

2017-12-16 12:32 UTC, closed without merging