Added blog link
fossasia/gci17.fossasia.org pull request #321
Opened 2017-12-16 02:09 UTC by lillietricianijiiro

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-16 05:05 UTC, akshatnitd commented
@lillietricianijiiro Please resolve the conflicts :)

2017-12-16 07:51 UTC, anshumanv requested changes
Please upload your image.

2017-12-16 07:54 UTC, the-codingninja requested changes
Upload your image and resolve conflicts

2017-12-16 10:52 UTC, isuruAb reviewed
Please upload your image and resolve confllicts

2017-12-17 23:23 UTC, abhinavk96 requested changes
The actual png image file needs to be uploaded.

2017-12-20 06:10 UTC, abishekvashok requested changes

2017-12-20 06:10 UTC, abishekvashok commented on _data/blogs.yml
> +  img: Part 1 of blog.jpg, Part 2 of blog.jpg, Part 3 of blog.jpg, Part 4 of blog.jpg, Part 5 of blog.jpg
Please provide a definite img name, like blogname_wihout_spaces_short.png

2017-12-20 06:11 UTC, abishekvashok commented
There are also ocnflicts pls resolve them :)

2017-12-26 14:24 UTC, AmanSingh200 commented
https://wordpress.com/read/feeds/77017858/posts/1711640617

can someone plzz add this blog

2017-12-27 05:11 UTC, ParthS007 commented
@lillietricianijiiro  Closing this PR , Please read `README.md` and create a new PR 👍

2017-12-27 05:11 UTC, closed without merging