Solves #361. FB div width is proper now
fossasia/gci17.fossasia.org pull request #368
Opened 2017-12-19 13:56 UTC by shikhar-scs

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

The Fb scroll feed of fossasia page was not showing complete width. This issue has been fixed.
![social media 1](https://user-images.githubusercontent.com/25258877/34155235-89ed67ce-e4de-11e7-8b34-f8faf5eb2c7c.png)

 Also as mentioned by me in #361 the iframes lacked responsiveness and never changed irrespective of change n dimensions. 

Thus, that issue has also been cleared with the help of media queries. By nature iframes are not responsive an d always maintain there dimensions. So media queries were used. I've used 2 break points and they have been mentioned in my commit.

As the dimensions at any given time is fixed thus actual moving responsiveness cant be seen. However at the breaking points of 1200px and 768px they can be seen shifting . The top bar contains the width in each of the cases.
![social media 2](https://user-images.githubusercontent.com/25258877/34155484-7bd25806-e4df-11e7-991a-3c4d5c6b6227.png)
![social media 3](https://user-images.githubusercontent.com/25258877/34155486-7d6e002a-e4df-11e7-8477-f49ef19dba0d.png)

 
- Replace this with your change description

2017-12-19 14:23 UTC, YashKumarVerma approved these changes

2017-12-19 14:36 UTC, shikhar-scs commented
@ParthS007 @duttaditya18  @anshumanv 
please review

2017-12-19 17:30 UTC, STEdirisuriya commented
Can you change G+ page to showing posts like twitter and FB. The G+ page only showing Follow.

2017-12-19 20:01 UTC, ParthS007 requested changes
@shikhar-scs  great work ! Please provide a preview link 👍

2017-12-19 21:11 UTC, 0x48piraj reviewed
Looks good to me!
A preview link will much be appreciated.

2017-12-20 01:55 UTC, shikhar-scs commented
@ParthS007 @0x48piraj here is the preview link
[https://shikhar-scs.github.io/gci17.fossasia.org/](https://shikhar-scs.github.io/gci17.fossasia.org/)

2017-12-20 02:07 UTC, ParthS007 approved these changes

2017-12-20 02:07 UTC, Ploypiti approved these changes

2017-12-20 02:11 UTC, 0x48piraj approved these changes
LGTM! :rocket:

2017-12-20 02:14 UTC, shikhar-scs commented
Merge ?

2017-12-20 02:28 UTC, merged

2017-12-20 02:28 UTC, 0x48piraj commented
@shikhar-scs Here you go!

2017-12-20 02:30 UTC, shikhar-scs commented
Thankyou @ParthS007 @0x48piraj