Adding Avatar
fossasia/gci17.fossasia.org pull request #40
Opened 2017-11-29 18:55 UTC by chahatbansal

2017-11-29 19:40 UTC, sansyrox requested changes
@chahatbansal please squash your commits , and try to make a short meaningful commit.
Also, set a maximum height and width as your image is covering too much space.

2017-11-29 20:14 UTC, chahatbansal commented
@stealthanthrax Please specify height and width.

2017-11-29 21:07 UTC, stealthanthrax commented
@chahatbansal , try having a height of 120px or using bootstrap class of "col-2".

2017-11-30 06:12 UTC, abhinavk96 requested changes

2017-11-30 06:12 UTC, CosmicCoder96 commented on index.html
> +					  <div class="col-2">
@chahatbansal Please maintain the indentation

2017-11-30 06:12 UTC, CosmicCoder96 commented on index.html
> +					  <div class="col-2">
Also squash your commits :)

2017-11-30 06:43 UTC, closed without merging