Added a new video
fossasia/gci17.fossasia.org pull request #401
Opened 2017-12-21 15:25 UTC by samyakbvs

#324

2017-12-21 16:45 UTC, nikit19 requested changes
Please put your image in the img/video folder.
otherwise LGTM

2017-12-21 16:59 UTC, samyakbvs commented
@nikit19

2017-12-21 17:01 UTC, nikit19 approved these changes

2017-12-21 17:01 UTC, nikit19 commented
@samyakbvs  Good job !

2017-12-21 17:02 UTC, samyakbvs commented
pls merge

2017-12-21 17:02 UTC, anshumanv requested changes
Check comments.

2017-12-21 17:02 UTC, anshumanv commented on _data/video.yml
> +- url: https://www.youtube.com/watch?v=iJBtZgYQk0U&feature=youtu.be
Change video url to - https://www.youtube.com/watch?v=iJBtZgYQk0U

2017-12-21 17:02 UTC, samyakbvs commented
@nikit19

2017-12-21 17:05 UTC, samyakbvs commented
done

2017-12-21 17:05 UTC, samyakbvs commented
@anshumanv pls merge

2017-12-21 21:13 UTC, anshumanv approved these changes
LGTM

2017-12-21 21:14 UTC, dilpreetsio approved these changes

2017-12-21 21:17 UTC, vaibhavsingh97 approved these changes

2017-12-21 21:18 UTC, vaibhavsingh97 commented
@samyakbvs Please squash your commits into one.

2017-12-22 04:29 UTC, samyakbvs commented
I won't be able to squash as I have other commits in between
so pls merge like this

2017-12-22 07:06 UTC, ParthS007 approved these changes

2017-12-22 07:06 UTC, merged