Update blogs.yml
fossasia/gci17.fossasia.org pull request #404
Opened 2017-12-21 16:28 UTC by Beta-King

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-21 16:54 UTC, anshumanv requested changes
Check comments

2017-12-21 16:54 UTC, anshumanv commented on _data/blogs.yml
> +  img: Beta_KIng.jpg
Please upload the image for this blog.

2017-12-24 23:19 UTC, 0x48piraj requested changes
Resolve conflicts !!

2017-12-27 05:20 UTC, ParthS007 requested changes
@Beta-King  Please follow `README.md` on where to add blog image, Please update this asap 👍

2017-12-27 05:25 UTC, Beta-King commented
i've done this in another PR which is merged, sorry i forgot to close this one.

2017-12-27 05:25 UTC, closed without merging