Pull request for GCI
fossasia/gci17.fossasia.org pull request #437
Opened 2017-12-23 10:11 UTC by SidDevelop

This is done for GCI

2017-12-23 10:28 UTC, nikit19 requested changes
Travis CI has failed. Please make the changes.
You need to add more fields about yourself in students.yml

2017-12-23 10:47 UTC, invinciblycool commented
@SidDevelop Please change the title of the PR to a meaningful one.

2017-12-23 11:19 UTC, abishekvashok requested changes
Also the image should be 240x240px

2017-12-23 11:19 UTC, abishekvashok commented on _data/students.yml
> +image: sid.jpg
Image name and the name you entered doesn't match

2017-12-23 19:45 UTC, ParthS007 requested changes
@SidDevelop  Please do the changes as suggested by @abishekvashok  and PR is ready to merge 👍

2017-12-24 23:17 UTC, 0x48piraj requested changes
Rename `1467822650826.jpg` to `sid.jpg` or vice versa.

And, maybe your image is not in correct dimensions. If so, correct that too. :+1:

2017-12-27 05:23 UTC, ParthS007 requested changes
@SidDevelop  Please rename your image to `sid.jpg`, also properly indent your code and your PR is ready to merge 👍

2017-12-28 15:37 UTC, sayak119 requested changes
Please indent properly

2017-12-29 07:49 UTC, harshit98 commented
Hi @SidDevelop , what's the status of this pull request ?

2017-12-30 11:25 UTC, ParthS007 reviewed
@SidDevelop  Please update your PR 👍

2017-12-30 18:54 UTC, isuruAb reviewed
please resolve conflicts

2017-12-31 19:29 UTC, ParthS007 reviewed
closing this PR due to inactivity, Please create a new PR 👍

2017-12-31 19:29 UTC, closed without merging