New Student entry.
fossasia/gci17.fossasia.org pull request #452
Opened 2017-12-24 06:34 UTC by ameybhavsar24

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-24 07:17 UTC, gabru-md commented on _data/student_projects.yml
> +  image: amey.png
Image not found.

2017-12-24 07:18 UTC, gabru-md commented on _data/students.yml
> +  image: amey.jpg
Image not found

2017-12-24 07:18 UTC, gabru-md requested changes
Please add the images that you have mentioned in the PR.

2017-12-24 23:14 UTC, 0x48piraj requested changes
Remove the conflicts!

2017-12-25 11:51 UTC, anshumanv requested changes
Please upload appropriate images in respective directories.

2017-12-25 12:17 UTC, the-codingninja requested changes
Resolve conflicts and add appropriate image

2017-12-26 18:46 UTC, STEdirisuriya commented
- Add a description
- Check requirements in PR introduction
- Add a image
- Resolve conflicts
- If you can squash after doing those things.

2017-12-26 18:46 UTC, supunTE requested changes
Add a description
    Check requirements in PR introduction
    Add a image
    Resolve conflicts
    If you can squash after doing those things.

2017-12-27 05:27 UTC, ParthS007 requested changes
@ameybhavsar24  Please follow `README.md` on how to add blog an student and update your PR 👍

2017-12-28 08:04 UTC, closed without merging