Create Experience with GCI 2017
fossasia/gci17.fossasia.org pull request #453
Opened 2017-12-24 07:58 UTC by abhinavraj0123456789

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a live link or preview screenshot
- [ ] Images are `240 x 240` [w x h]
- [ ] Resolved merge conflicts
- [ ] Included a description of my change below

# Things done in this Pull Request

- Replace this with your change description

2017-12-24 08:19 UTC, abishekvashok requested changes
Please see the readme on how to add your blog.

2017-12-24 10:24 UTC, ParthS007 requested changes
@abhinavraj0123456789  Please read README.md for adding the blog 👍

2017-12-24 10:28 UTC, abishekvashok requested changes

2017-12-24 10:28 UTC, abishekvashok commented on Experience with GCI 2017
> +  author_name: Abhinav Raj
It should be added to blogs.yml 
img: should contain the images name

2017-12-24 10:28 UTC, abishekvashok requested changes

2017-12-24 10:28 UTC, abishekvashok commented on Experience with GCI 2017
> +  author_name: Abhinav Raj
Please add to blogs.yml img name should be your images name.

2017-12-24 11:19 UTC, nikit19 requested changes
You have to add these details in  'blogs.yml' in _data folder.

2017-12-24 23:13 UTC, 0x48piraj reviewed
Set a suitable PR title!

Hint: "What you did to the codebase"

2017-12-27 05:30 UTC, ParthS007 requested changes
@abhinavraj0123456789  I think you are adding blog, so please follow `README.md` on how to add blog and update your PR 👍

2017-12-27 09:02 UTC, STEdirisuriya commented
If you are going to add a blog add it to blogs.yml as readme.md

2017-12-29 07:50 UTC, harshit98 commented
Hi @abhinavraj0123456789 , what's the status of the pull request?

2017-12-30 11:24 UTC, ParthS007 reviewed
closing this PR due to inactivity, Please create a new PR after go through `README.md` , Thanks

2017-12-30 11:24 UTC, closed without merging