Fixes #474 :Developed Contributors' Section
fossasia/gci17.fossasia.org pull request #475
Opened 2017-12-24 22:54 UTC by saarthakchats

Fixes #474

2017-12-24 22:56 UTC, 0x48piraj requested changes
Provide Test/Review Link

2017-12-24 23:00 UTC, saarthakchats commented
https://saarthakchats.github.io/gci17.fossaaaaaasia.org/
@0x48piraj

2017-12-24 23:09 UTC, 0x48piraj approved these changes
Looks good.

2017-12-25 00:58 UTC, CloudyPadmal requested changes

2017-12-25 00:58 UTC, CloudyPadmal commented on index.html
> +	<a  class="btn" data-toggle="popover" title="" data-placement="bottom" href="https://github.com/gci17.fossasia.org">View the Github Repository <i class="fa fa-github fa-lg"></i></a>
Wrong link : https://github.com/fossasia/gci17.fossasia.org

2017-12-25 00:59 UTC, CloudyPadmal requested changes

2017-12-25 00:59 UTC, CloudyPadmal commented on index.html
> +	<a  class="btn" data-toggle="popover" title="" data-placement="bottom" href="https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/"> How can I be a contributor?</a>
And remove the space in front of `How`

2017-12-25 07:07 UTC, saarthakchats commented
@CloudyPadmal

2017-12-25 07:34 UTC, anshumanv commented
What did you exactly do?
Please don't remove the PR template and fill it appropriately.

2017-12-25 07:35 UTC, anshumanv approved these changes

2017-12-25 07:54 UTC, saarthakchats commented
The button "How can I contribute" leads nowhere. I have fixed that and also added a button to the github repos. @anshumanv

2017-12-25 07:54 UTC, saarthakchats commented
I have fixed a button and added another useful one

2017-12-25 07:55 UTC, gabru-md approved these changes

2017-12-25 07:55 UTC, saarthakchats commented
@anshumanv @gabru-md 
If you think it is fine, can you approve my task as well https://codein.withgoogle.com/dashboard/task-instances/6443522922119168/

2017-12-25 07:58 UTC, saarthakchats commented
@gabru-md @anshumanv Can we merge. 
No pressure ;)

2017-12-25 08:01 UTC, CloudyPadmal approved these changes

2017-12-25 08:05 UTC, merged

2017-12-25 08:16 UTC, saarthakchats commented
@gabru-md Please approve my task

2017-12-25 08:17 UTC, saarthakchats commented
https://codein.withgoogle.com/dashboard/task-instances/6443522922119168/