Responsiveness of images in blogs increased
fossasia/gci17.fossasia.org pull request #500
Opened 2017-12-25 17:31 UTC by sandeepyadav097

Thank you for your pull request! Please read and understand everything below

Please acknowledge that you have read and understood each of the following before submitting your pull request.

# _Do not_ delete any text other than where you are instructed.

**Maintainers: If any of these are left unchecked, do not merge.**

**Students: If one of them is not applicable to you -- Please check it anyways. DO NOT REMOVE ANYTHING!**

**You may check them after opening your pull request.**

You may do so by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a live link or preview screenshot
- [x] Images are `240 x 240` [w x h]
- [x] Resolved merge conflicts
- [x] Included a description of my change below

# Things done in this Pull Request
Added and improved responsive labels
preview-
![image](https://user-images.githubusercontent.com/26329908/34341904-7e10a45a-e9c7-11e7-8f37-1116106bec4b.png)

Actual-
![image](https://user-images.githubusercontent.com/26329908/34341908-852368fe-e9c7-11e7-9f7f-e32c3e621468.png)

2017-12-25 17:48 UTC, anshumanv commented
I'd like to request a preview link to test the changes you made. :smile:

2017-12-25 17:54 UTC, sandeepyadav097 commented
The link is http://sandeepyadav.tech/gci17.fossasia.org/

2017-12-25 17:58 UTC, anshumanv commented on index.html
> +		    <div class="col-md-4 col-lg-3 col-sm-4 col-xs-6">
Indent this line properly.

2017-12-25 17:58 UTC, anshumanv approved these changes
Works well.

2017-12-26 04:21 UTC, sandeepyadav097 commented
Merge them

2017-12-26 04:30 UTC, NaviRocker requested changes
@sandeepyadav097 Try to Squash your commits. It would be Awesome.

2017-12-26 04:40 UTC, sandeepyadav097 commented
Can you tell me How? @naveentherocker

2017-12-26 04:44 UTC, naveentherocker commented
Try this @sandeepyadav097 
`git reset --soft HEAD~5`
`git commit -m "<Your commit message>"`
`git push -f origin gh-pages`

2017-12-26 04:46 UTC, naveentherocker commented
And try to mention the Issue that you are working on.

2017-12-26 04:52 UTC, NaviRocker approved these changes
Please Mention `Fixes #499` in the PR Body.

2017-12-26 06:21 UTC, NaviRocker requested changes
There are many unwanted lines. Try to remove them

2017-12-26 06:21 UTC, naveentherocker commented on index.html
> +
Remove unwanted lines Please.

2017-12-26 06:21 UTC, naveentherocker commented on index.html
> +
Remove these

2017-12-26 06:31 UTC, sandeepyadav097 commented on index.html
> +
I haven't made any changes on those lines I guess

2017-12-26 06:44 UTC, sandeepyadav097 commented
@anshumanv who will merge these

2017-12-26 06:46 UTC, anshumanv commented
> @anshumanv who will merge these

Some mentor after this has gained enough approves.

2017-12-26 09:46 UTC, ParthS007 reviewed
@sandeepyadav097  Why have you changed other files, Please make changes which are related to the issue.

2017-12-26 09:49 UTC, ParthS007 reviewed
This is actual site in `Samsung Galaxy Note 3`
![image](https://user-images.githubusercontent.com/24358501/34353739-f16e6990-ea4f-11e7-80fd-839ee724a931.png)
This is in your Preview link 
![image](https://user-images.githubusercontent.com/24358501/34353748-07c34698-ea50-11e7-9ad8-222a777332ee.png)


Its just a example, Please make necassary changes so that names do not overlap with blog title.

2017-12-26 14:17 UTC, sandeepyadav097 commented
@ParthS007  what do you suggest me to close the PR and restore it ??

2017-12-26 15:03 UTC, closed without merging