Added section: added a sister project Phimp.me
fossasia/gci17.fossasia.org pull request #530
Opened 2017-12-26 18:32 UTC by saarthakchats

2017-12-26 18:46 UTC, 0x48piraj requested changes
Provide a test-link :+1:

2017-12-26 18:54 UTC, saarthakchats commented
https://saarthakchats.github.io/pattupuparipops/
@0x48piraj

2017-12-26 19:23 UTC, 0x48piraj requested changes
![image](https://user-images.githubusercontent.com/5800726/34363237-5aa4cf12-eaa0-11e7-805d-db163324da68.png)
It's not looking good from my eyes :-1:

2017-12-26 19:27 UTC, arjunpandey2003 commented
Adjust the margin top and right

2017-12-26 19:27 UTC, arjunpandey2003 commented
Rest looks good

2017-12-27 02:05 UTC, NaviRocker requested changes
I don't think that this section is important here. Let's wait for other reviews.

2017-12-27 08:31 UTC, supunTE requested changes

2017-12-27 08:31 UTC, STEdirisuriya commented on index.html
> +
Remove unwanted spaces

2017-12-27 08:31 UTC, STEdirisuriya commented on index.html
> +
This

2017-12-27 08:31 UTC, STEdirisuriya commented on index.html
> +
<p> tag must be closed

2017-12-27 09:21 UTC, duttaditya18 commented
@saarthakchats Not required. It doesn't looks good either.

2017-12-28 10:09 UTC, closed without merging