Added link to my blogpost.
fossasia/gci17.fossasia.org pull request #536
Opened 2017-12-27 10:08 UTC by TechnoAman

Added link to my blogpost 
with url,title,img,author_name

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-27 10:46 UTC, akshatnitd requested changes

2017-12-27 10:46 UTC, akshatnitd commented on _data/blogs.yml
> +- url    : https://amantiwari123.wordpress.com/2017/12/27/my-journey-to-google-code-in-gci-2017-18/
You have left extra spaces between `url` and `:` and similarly other key values. Make sure to follow the correct practice and change it the way other entries are mentioned.

2017-12-27 10:46 UTC, akshatnitd commented on _data/blogs.yml
> +  img    : https://amantiwari123.files.wordpress.com/2017/12/img_20171227_140128.jpg?w=1272
You don't need to provide a link here. Instead add an image of size 240*240px in the `img/blog/` folder and write the filename in the value for `img` key.

2017-12-27 10:48 UTC, akshatnitd commented
Also, fill the Pull Request template correctly and follow good practices. You also need to provide a deployment link.

2017-12-27 14:07 UTC, ParthS007 requested changes
@TechnoAman  Please do the suggested changes

2017-12-27 22:53 UTC, 0x48piraj requested changes
Provide a Test-Link. 
> Follow the suggestions given by our mentors.

2017-12-28 00:15 UTC, isuruAb reviewed
Hello @TechnoAman , please provide a test link it speeds up the review process and it makes reviewers job easy. cheers

2017-12-28 07:11 UTC, ParthS007 commented
closing this as a duplicate of #553

2017-12-28 07:11 UTC, closed without merging

2017-12-28 07:49 UTC, TechnoAman commented
I have added the image after resize 240 x 240

On 28 Dec 2017 12:41 pm, "Parth" <notifications@github.com> wrote:

> closing this as a duplicate of #553
> <https://github.com/fossasia/gci17.fossasia.org/pull/553>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/536#issuecomment-354241293>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Agho9oPJMmkI2aFPLfW7mHncx8Gtv1qWks5tEz8sgaJpZM4RNXEk>
> .
>