Update blogs.yml
fossasia/gci17.fossasia.org pull request #553
Opened 2017-12-27 22:19 UTC by TechnoAman

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-27 22:21 UTC, TechnoAman commented
Here I am add the link to the blog 
title, img author name

2017-12-27 22:50 UTC, 0x48piraj commented on _data/blogs.yml
> +  img: Aman1.jpg
Where's the `img` ?

2017-12-27 22:50 UTC, 0x48piraj requested changes
The image is not present. :-1:

2017-12-28 08:12 UTC, nikit19 requested changes
You have to send one pull request which has the code that you have written here and also the image that you have submitted in the other pull request.

2017-12-28 11:56 UTC, closed without merging