Hitesh's GCI-2017
fossasia/gci17.fossasia.org pull request #589
Opened 2017-12-28 22:49 UTC by Hr220903

Hi, my name is Hitesh and this is my blog
https://hiteshsgci2017experience.wordpress.com/
https://fossasia.org/

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-29 00:31 UTC, isuruAb reviewed
you didn't do any changes please check again

2017-12-29 05:07 UTC, STEdirisuriya commented
Please refer README.md

2017-12-29 07:11 UTC, nikit19 requested changes
Please read the readme.md to see how to add your blog.

2017-12-29 08:13 UTC, nikit19 commented
Please resolve conflicts and make sure that the dimensions of the image is 240 x 240 pixels

2017-12-29 09:29 UTC, nikit19 approved these changes

2017-12-29 10:18 UTC, abishekvashok commented
Please fix the conflicts

2017-12-29 11:56 UTC, anshumanv requested changes
Check comments.

2017-12-29 11:56 UTC, anshumanv commented on _data/blogs.yml
> +  img: image1.jpeg
Please rename image to exactly the file name of the image that you uploaded.

2017-12-29 12:46 UTC, isuruAb reviewed
please resolve conflicts

2017-12-30 07:57 UTC, harshit98 approved these changes

2017-12-30 07:57 UTC, merged