updated -added my blog
fossasia/gci17.fossasia.org pull request #590
Opened 2017-12-29 06:59 UTC by prank15062002

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-29 07:05 UTC, nikit19 requested changes
Just upload the image that you have mentioned  in the img/blogs folder and you are done :+1:

2017-12-29 07:09 UTC, nikit19 commented on _data/blogs.yml
> +  url: https://openblogsource.wordpress.com/2017/12/28/my-journey-open-source
you need to add " `-` " before url

2017-12-29 11:30 UTC, anshumanv commented
Please fill PR template correctly.

2017-12-30 11:46 UTC, ParthS007 commented
closing thiis as a duplicate of #613

2017-12-30 11:46 UTC, closed without merging