blog details
fossasia/gci17.fossasia.org pull request #613
Opened 2017-12-29 17:11 UTC by prank15062002

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-29 17:14 UTC, prank15062002 commented
please ell me when the file will be merged so that i can submit my work

2017-12-29 17:22 UTC, nikit19 requested changes
Please make the changes and upload the image.
You can close any one of the pull requests and work on the other .

2017-12-29 17:22 UTC, nikit19 commented on _data/blogs.yml
> + - url: https://openblogsource.wordpress.com/2017/12/28/my-journey-open-source
Please remove the space before `-`

2017-12-30 11:49 UTC, ParthS007 requested changes
@prank15062002  Please avoid creating multiple PRs of the same issue and Please go through `README.md` on how to add add a blog 👍

2017-12-30 20:17 UTC, 0x48piraj requested changes

2017-12-30 20:17 UTC, 0x48piraj commented on _data/blogs.yml
> +
remove extra space.

2017-12-31 02:18 UTC, isuruAb reviewed
please resolve conflicts

2018-01-03 10:19 UTC, ParthS007 reviewed
@prank15062002  closing this PR as there are lot conflicts. Please read `README.md` on how to add a blog and ask on Gitter channel if you face any difficulties.

2018-01-03 10:19 UTC, closed without merging