Fixes #618 :Developed navbar
fossasia/gci17.fossasia.org pull request #619
Opened 2017-12-29 18:42 UTC by saarthakchats

Fixes #618 
# Changes done in this Pull Request
Have added a drop-down to create more space, the "Eng" drop-down is back on the navbar. Linked all projects to the Projects dropdown

2017-12-29 19:07 UTC, arjunpandey2003 commented
deploy link

2017-12-29 19:16 UTC, vaibhavsingh97 commented
@saarthakchats Please provide us the deployment link

2017-12-29 19:16 UTC, saarthakchats commented
https://saarthakchats.github.io/itsmethedonsi/

2017-12-29 19:16 UTC, saarthakchats commented
@vaibhavsingh97

2017-12-29 19:23 UTC, arjunpandey2003 commented
@saarthakchats you dont have social links in your navbar

2017-12-29 19:25 UTC, saarthakchats commented
Its in the quick link @arjunpandey2003. For space

2017-12-29 19:43 UTC, supunTE requested changes
Improve code quality

2017-12-29 19:43 UTC, STEdirisuriya commented on _includes/header.html
> +		                            <a href="#">
Indent

2017-12-29 19:43 UTC, STEdirisuriya commented on _includes/header.html
> +								<li class="has-dropdown">
Indent

2017-12-29 19:43 UTC, STEdirisuriya commented on index.html
remove unwanted spaces

2017-12-29 19:48 UTC, STEdirisuriya commented on _includes/header.html
> +		                        		</li>
no indented yet

2017-12-29 19:49 UTC, STEdirisuriya commented on _includes/header.html
> +		                            <a href="#">
indent

2017-12-29 19:49 UTC, supunTE requested changes
Indent those too

2017-12-29 19:52 UTC, supunTE requested changes
don't makes mistakes

2017-12-29 19:52 UTC, STEdirisuriya commented on _includes/header.html
> +						</ul>
indent

2017-12-29 19:52 UTC, STEdirisuriya commented on _includes/header.html
>  		                                    </a>
indent

2017-12-29 19:53 UTC, saarthakchats commented
Done @STEdirisuriya

2017-12-29 19:55 UTC, supunTE approved these changes
LGTM!

2017-12-29 23:02 UTC, ParthS007 approved these changes

2017-12-30 03:49 UTC, saurabhjn76 approved these changes
LGTM 👍🏻

2017-12-30 03:49 UTC, merged