Fixed #645: Restored the section
fossasia/gci17.fossasia.org pull request #657
Opened 2017-12-30 19:45 UTC by samyakbvs

The Thanks section had disappeared I added it

2017-12-30 19:49 UTC, ParthS007 commented
@samyakbvs  Please provide a preview link 👍

2017-12-30 20:12 UTC, 0x48piraj commented on index.html
> -			<h2 class="txt-rotate" data-period="1000" data-rotate='[ "Thank You For Contributing!", "योगदान करने के लिए धन्यवाद!", "Danke für den Beitrag!", "Dziękujemy za Twój wkład!", "貢献していただきありがとうございます!",
You just deleted it !

2017-12-30 20:13 UTC, 0x48piraj requested changes
I guess, a Malformed PR

2017-12-31 06:09 UTC, samyakbvs commented
It is not working, see the fossasia site

2017-12-31 06:11 UTC, samyakbvs commented
Just wait for sometime I will fix this issue

2017-12-31 07:26 UTC, closed without merging