Update blogs.yml
fossasia/gci17.fossasia.org pull request #661
Opened 2017-12-31 03:18 UTC by hshafaq7

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-31 05:37 UTC, isuruAb reviewed
please resolve the travis failure

2017-12-31 07:36 UTC, nikit19 requested changes
Please make these changes

2017-12-31 07:36 UTC, nikit19 commented on _data/blogs.yml
> +  img:
Please upload the image and write the name of the image after `img : `

2017-12-31 07:36 UTC, nikit19 commented on _data/blogs.yml
> +  title:Here I come Coding In
please the exact format as given in the readme.md there should be a space after `:`

2017-12-31 13:16 UTC, 0x48piraj requested changes
Fix Travis CI failures. :+1:

2018-01-01 08:13 UTC, akshatnitd reviewed
Please make the suggested changes by @nikit19 .

2018-01-01 08:19 UTC, harshit98 commented
Closing this pull request. Similar to #704

2018-01-01 08:19 UTC, closed without merging