Linking my blog to the gci fossasia website
fossasia/gci17.fossasia.org pull request #664
Opened 2017-12-31 05:46 UTC by hshafaq7

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-31 07:37 UTC, nikit19 requested changes
Please upload the image. And you can make changes in the same pull request too

2017-12-31 13:14 UTC, 0x48piraj commented on _data/blogs.yml
> + img: hshafaq1
wrong syntax

2017-12-31 13:15 UTC, 0x48piraj requested changes
Image syntax is wrong, as mentioned in my code review.

2017-12-31 14:29 UTC, abishekvashok requested changes

2017-12-31 14:29 UTC, abishekvashok commented on _data/blogs.yml
> +-url: https://mygeekyworld786.wordpress.com/2017/12/30/here-i-come-coding-in/
Add a space after `-`

2018-01-01 08:21 UTC, harshit98 commented
Closing this PR. Similar to #704

2018-01-01 08:21 UTC, closed without merging