Edited Vibhor Verma's Profile
fossasia/gci17.fossasia.org pull request #691
Opened 2017-12-31 17:36 UTC by mjd220903

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2017-12-31 19:13 UTC, ParthS007 requested changes
@mjd220903  PLease provide a preview link 👍

2017-12-31 19:17 UTC, mjd220903 commented
how do i provide it ??

2017-12-31 19:18 UTC, mjd220903 commented
please tell me so that i can provide it @ParthS007

2017-12-31 19:19 UTC, mjd220903 commented
https://github.com/fossasia/gci17.fossasia.org/pull/691/files/eba12fbb03e143e60c7e7ad71836235fba1d3e40

2017-12-31 19:23 UTC, mjd220903 commented
![screen shot 2018-01-01 at 12 50 56 am](https://user-images.githubusercontent.com/34032949/34463812-01ec5038-ee8e-11e7-918c-4bc9b3acb21a.png)

This is before

![screen shot 2018-01-01 at 12 51 38 am](https://user-images.githubusercontent.com/34032949/34463815-1eeb51d4-ee8e-11e7-8925-e9bc9366c02d.png)

This is after

2017-12-31 19:24 UTC, mjd220903 commented
Is it fine @ParthS007 
If it is not let me know

2017-12-31 19:38 UTC, ParthS007 commented
@mjd220903  You are doing everything correct but your PR contains previous commits (like this PR also have changes which add your profile also but ) so please remove please update your local and fork and then make a new PR 👍

2018-01-01 03:31 UTC, mjd220903 commented
can you guide me i don't understand

2018-01-01 04:12 UTC, mjd220903 commented
**@ParthS007  are you there ??**

2018-01-01 06:00 UTC, mjd220903 commented
@ParthS007

2018-01-01 07:50 UTC, harshit98 commented
@mjd220903 Don't open and close PR again and again.

- Change the name of Vibhor Verma's image to `vibhor.jpg`.

2018-01-01 09:16 UTC, mjd220903 commented
@harshit98 should i change to code or the photo name ??

2018-01-01 09:40 UTC, harshit98 commented on _data/mentors.yml
> +  image: CsZwA5Xn.jpg
Change the image name: @mjd220903

2018-01-01 09:45 UTC, harshit98 approved these changes
LGTM! 💯 

@mjd220903 Good work! I'll merge this pull request as soon as it will pass Travis CI.

2018-01-01 09:46 UTC, mjd220903 commented
Ok thank you  @harshit98

2018-01-01 10:10 UTC, mjd220903 commented
@harshit98 Merge it please as all the checks have passed

2018-01-01 10:17 UTC, merged