install ins. in hindi, fixed others Fixes #702
fossasia/gci17.fossasia.org pull request #703
Opened 2018-01-01 06:20 UTC by YashKumarVerma

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
-Added install instructions hindi
- Windows installation had command `ls` which is linux specific. replaced it with `dir`.

Fixes #702

2018-01-01 06:38 UTC, nzec approved these changes
`स्थानीय विकास सेटअप` 🤣 That sounds hilarious. Well, it looks good.

2018-01-01 07:46 UTC, harshit98 commented on installation/installation_windows(hi).md
> +8. ओउ आपका सर्वर ऊपर है और चल रहा है Gci17.fossasia.org पृष्ठ देखने के लिए, `स्थानीयहोस्ट: 4000` पर जाएं.
Gci17.fossasia.org -> gci17.fossasia.org

2018-01-01 07:56 UTC, YashKumarVerma commented on installation/installation_windows(hi).md
> +8. ओउ आपका सर्वर ऊपर है और चल रहा है Gci17.fossasia.org पृष्ठ देखने के लिए, `स्थानीयहोस्ट: 4000` पर जाएं.
fixed. 👍

2018-01-01 08:03 UTC, akshatnitd requested changes

2018-01-01 08:03 UTC, akshatnitd commented on installation/installation_macos(hi).md
> +6. अब आपका सर्वर ऊपर और चल रहा है। Gci17.fossasia.org पृष्ठ देखने के लिए, `स्थानीयहोस्ट: 4000` पर जाएं
Change `Gci17.fossasia.org` to `gci17.fossasia.org`

2018-01-01 08:03 UTC, akshatnitd commented on installation/installation_linux(hi).md
> +6. अब आपका सर्वर ऊपर और चल रहा है। Gci17.fossasia.org पृष्ठ देखने के लिए, `स्थानीयहोस्ट: 4000` पर जाएं
Change `Gci17.fossasia.org` to `gci17.fossasia.org`

2018-01-02 07:52 UTC, ParthS007 approved these changes

2018-01-02 07:57 UTC, merged