Fixed #715: Responsiveness
fossasia/gci17.fossasia.org pull request #716
Opened 2018-01-01 12:17 UTC by samyakbvs

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request
Responsiveness enhanced
- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**) https://samyakbvs.github.io/responsiveness-gci17.fossasia.org/
- Fixes #<Issue no.>715

2018-01-01 12:18 UTC, samyakbvs commented
Before: 
![screen shot 2018-01-01 at 5 45 27 pm](https://user-images.githubusercontent.com/34275800/34467572-ed9fbf6e-ef1b-11e7-8ece-c4f55e72bb08.png)
After: 
![screen shot 2018-01-01 at 5 45 09 pm](https://user-images.githubusercontent.com/34275800/34467573-f23c253a-ef1b-11e7-8e73-e01860c2d497.png)

2018-01-01 12:38 UTC, harshit98 commented
@samyakbvs The UI design is getting disturbed for laptop screen size:

After changes:

![screen shot 2018-01-01 at 6 07 04 pm](https://user-images.githubusercontent.com/22245418/34467691-b677a47c-ef1e-11e7-9977-727e7c05783c.png)

Before changes:

![screen shot 2018-01-01 at 6 07 00 pm](https://user-images.githubusercontent.com/22245418/34467693-bf060dfe-ef1e-11e7-8592-4b2381f084fc.png)

2018-01-01 12:40 UTC, samyakbvs commented
Okay lemme work on that

2018-01-01 12:41 UTC, 0x48piraj requested changes
A very bad PR title I must say !
And no need to change it to `absolute`
It will distort the layout in other dimensions !

Close this PR :+1:

2018-01-01 12:44 UTC, samyakbvs commented
@0x48piraj If you will wait I will find solutions to all the problems

2018-01-01 12:45 UTC, 0x48piraj commented
I don't think it's an issue @samyakbvs 
As seeing the Screenshot, I think you do not waited till the website loaded.

2018-01-01 12:48 UTC, samyakbvs commented
@0x48piraj If you have a doubt that I didn't wait until the website loaded, you should go and check the website yourself

2018-01-01 12:52 UTC, 0x48piraj commented
![image](https://user-images.githubusercontent.com/5800726/34467772-c11b280c-ef20-11e7-8232-535b2ca063b7.png)

@samyakbvs See this!

2018-01-01 12:57 UTC, samyakbvs commented
I checked it again @0x48piraj

2018-01-01 13:11 UTC, harshit98 commented
Don't argue with each other @0x48piraj @samyakbvs. If you want to argue, it should be technical. 

@samyakbvs Yes, take your time. Make sure the original laptop screen-size responsiveness is not disturbed. Also, change your commit name as well. It should be meaningful. How?
- When you'll squash your commits you can use `git commit --amend` to change the commit message.

@0x48piraj Thank you for reviewing the PR. 🎉

2018-01-01 13:13 UTC, samyakbvs commented
Okay @harshit98

2018-01-01 13:13 UTC, samyakbvs commented
Sorry by mistake clicked on close and comment

2018-01-01 13:16 UTC, 0x48piraj commented
I was not arguing, just was trying to point out the possible error 
Anyways, @samyakbvs what's your resolutions ?
I'll test that in a simulator, and will notify @harshit98 what's the status. :+1:

2018-01-01 13:18 UTC, samyakbvs commented
I have fixed it (almost)
There is a slight problem

2018-01-01 13:20 UTC, samyakbvs commented
Actually now its solved completely

2018-01-01 13:22 UTC, 0x48piraj commented
@samyakbvs Please don't throw practically useless comments :+1: 

Just make the changes, add a commit, provide a link. we're good to go !

2018-01-01 13:24 UTC, samyakbvs commented
"Anyways, @samyakbvs what's your resolutions ?" 
I was just replying to you

2018-01-01 13:30 UTC, samyakbvs commented
Done! @harshit98 and @0x48piraj  pls review

2018-01-01 13:38 UTC, 0x48piraj commented
@samyakbvs Not good !

P.S. Converted the attr(s) to css and linked it :-1:

2018-01-01 13:40 UTC, samyakbvs commented
I had to add more things that's why it was important to convert the attr(s) to css

2018-01-01 13:45 UTC, harshit98 commented
@samyakbvs The responsiveness of the website is still not in good condition:

- Small screen sizes:
![screen shot 2018-01-01 at 7 13 16 pm](https://user-images.githubusercontent.com/22245418/34468117-1784bdfa-ef28-11e7-8681-b087590c1933.png)

- Large mobile screen-size:

![screen shot 2018-01-01 at 7 13 35 pm](https://user-images.githubusercontent.com/22245418/34468118-1b3e413c-ef28-11e7-90e4-6b7573a422ef.png)

- Tablet screen-size:

![screen shot 2018-01-01 at 7 13 43 pm](https://user-images.githubusercontent.com/22245418/34468120-2284b156-ef28-11e7-89e0-afab666634b9.png)

2018-01-01 13:59 UTC, samyakbvs commented
Laptop screen size:
![screen shot 2018-01-01 at 7 26 18 pm](https://user-images.githubusercontent.com/34275800/34468202-d150a248-ef29-11e7-8679-9a2ec7de0569.png)
Tablet size: 
![screen shot 2018-01-01 at 7 26 05 pm](https://user-images.githubusercontent.com/34275800/34468206-dc5830d4-ef29-11e7-91f9-ca7d296673b6.png)
Mobile size:
![screen shot 2018-01-01 at 7 26 40 pm](https://user-images.githubusercontent.com/34275800/34468207-e729de4a-ef29-11e7-8ab2-f27eda2427d7.png)

Its working fine on my laptop and as you can see I am viewing the same link 
@harshit98 I think you forgot to refresh the page and even if you did pls do it one more time and then check :)

2018-01-02 10:54 UTC, vaibhavsingh97 requested changes

2018-01-02 10:54 UTC, vaibhavsingh97 commented on index.html
> +                <div class="row jig">
what do you mean by `jig`? can we have something relevant class name

2018-01-02 10:54 UTC, vaibhavsingh97 commented on css/theme-red.css
>  }
add one blank line after each class

2018-01-02 10:54 UTC, vaibhavsingh97 commented on css/theme-red.css
> +@media only screen and (max-width: 770px) {
same

2018-01-02 11:04 UTC, vaibhavsingh97 requested changes
Also, website is not responsive. Please fix all these issues
Screenshots:
![image](https://user-images.githubusercontent.com/8705386/34481761-f26c9936-efd9-11e7-83b6-b85979a8aa55.png)
![image](https://user-images.githubusercontent.com/8705386/34481777-0866bdd4-efda-11e7-8e6d-cdb9d3c8ee53.png)
There is enough space to have 2,3 colums
![image](https://user-images.githubusercontent.com/8705386/34481817-4b1b013a-efda-11e7-8a2f-90cfeb0f62d7.png)
![image](https://user-images.githubusercontent.com/8705386/34481832-565f1cb6-efda-11e7-9ab3-8cc6f2bb09c4.png)
![image](https://user-images.githubusercontent.com/8705386/34481847-6215831a-efda-11e7-96e9-fbbea734af7a.png)
![image](https://user-images.githubusercontent.com/8705386/34481855-6c258b16-efda-11e7-9e2e-d4a1d49f3bdf.png)
![image](https://user-images.githubusercontent.com/8705386/34481861-732197b6-efda-11e7-809a-e29cde2574f2.png)
![image](https://user-images.githubusercontent.com/8705386/34481881-8110a2b8-efda-11e7-8e76-0e1448b2711a.png)
![image](https://user-images.githubusercontent.com/8705386/34481896-9b6311d2-efda-11e7-91a0-25b805878b88.png)
![image](https://user-images.githubusercontent.com/8705386/34481907-b3f6a79a-efda-11e7-9eac-819821938cde.png)

2018-01-02 17:17 UTC, samyakbvs commented
I will do it @vaibhavsingh97 but I will need sometime

2018-01-03 19:07 UTC, samyakbvs commented
Making a new PR

2018-01-03 19:08 UTC, closed without merging