Update blogs.yml
fossasia/gci17.fossasia.org pull request #739
Opened 2018-01-02 10:13 UTC by oorjadandotiya

- url: https://technoorja.wordpress.com/2018/01/01/technoorja-learns-to-code/
#   title: Technoorja Learns To Code
#   img: Oorja_modified.jpeg
#   author_name: Oorja Dandotiya

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-02 10:22 UTC, isuruAb reviewed
where did you add this "Oorja_modified.jpeg" image

2018-01-02 10:38 UTC, nikit19 requested changes
Please write it somewhere else without # 
Please go through the readme.md and see how to add a blog

2018-01-03 00:24 UTC, 0x48piraj commented on _data/blogs.yml
> +# - url: https://technoorja.wordpress.com/2018/01/01/technoorja-learns-to-code/
Please remove the comments

2018-01-03 00:25 UTC, 0x48piraj commented on _data/blogs.yml
> +# - url: https://technoorja.wordpress.com/2018/01/01/technoorja-learns-to-code/
I meant remove `#`

2018-01-03 00:25 UTC, 0x48piraj requested changes
See the code review

2018-01-03 07:52 UTC, anshumanv reviewed
Please don't remove the comments, add an image.

2018-01-03 19:03 UTC, akshatnitd requested changes
Please don't remove the comments, those are there to show the correct format in which the blogs are to be added. Do check the way others have added it, and add an entry of your blog similarly. Also, you need to upload the image in the `img/blog/` folder.

2018-01-05 09:22 UTC, ParthS007 commented
closing this as a duplicate of #785

2018-01-05 09:22 UTC, closed without merging