Update video.yml
fossasia/gci17.fossasia.org pull request #740
Opened 2018-01-02 10:37 UTC by Yajushvyas

- url: https://www.youtube.com/watch?v=aOIzz64E-bE&t=76s
  title: FOSSASIA SUMMIT
  img: FOSSASIA.jpeg
  author_name: Yajush Vyas

2018-01-02 10:41 UTC, nikit19 requested changes
Please upload a new image in the img/video folder

2018-01-02 12:17 UTC, isuruAb reviewed
please upload image to img/video folder

2018-01-03 00:23 UTC, 0x48piraj requested changes
Squash your commits as well :+1:

2018-01-03 02:34 UTC, Yajushvyas commented
![cbgfh](https://user-images.githubusercontent.com/35025375/34507503-a779213c-f05c-11e7-9aaa-38f66ce1364e.PNG)

2018-01-03 04:04 UTC, Yajushvyas commented
![yajushvy](https://user-images.githubusercontent.com/35025375/34508776-4043ffb6-f069-11e7-96c6-ed61c71b8dab.PNG)

2018-01-03 07:44 UTC, Yajushvyas commented on _data/video.yml
> +  img: yajushvyas.png
![yajushvy](https://user-images.githubusercontent.com/35025375/34512331-cd5518ea-f087-11e7-915f-214bc5956668.PNG)

2018-01-03 19:00 UTC, akshatnitd requested changes
Please upload the image to `img/video` folder

2018-01-04 04:55 UTC, closed without merging