Linking my blog
fossasia/gci17.fossasia.org pull request #744
Opened 2018-01-02 15:17 UTC by hshafaq7

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-02 15:42 UTC, nikit19 requested changes
Please ensure that the dimensions of your image is 240 x 240 pixels.
Please upload only 1 image.

2018-01-02 15:42 UTC, nikit19 commented on _data/blogs.yml
> +
Please remove these blank lines

2018-01-02 18:00 UTC, harshit98 commented on _data/blogs.yml
> +
Remove extra lines.

2018-01-02 18:35 UTC, isuruAb reviewed
please do following changes
- upload a 240x 240 sized image
- remove extra image
- rotate your image 180 degrees
- resolve conflicts

2018-01-03 00:21 UTC, 0x48piraj requested changes
See the reviews @hshafaq7

2018-01-03 02:13 UTC, closed without merging