blog
fossasia/gci17.fossasia.org pull request #752
Opened 2018-01-02 18:40 UTC by kaushikichhabra

url: https://fossasiasblog.wordpress.com
title FOSS ASIA AND ME 
img: IMG_4670
author_name: Kaushiki Chhabra

2018-01-02 18:41 UTC, kaushikichhabra commented
url: https://fossasiasblog.wordpress.com
title FOSS ASIA AND ME 
img: IMG_4670
author_name: Kaushiki Chhabra

2018-01-02 18:42 UTC, kaushikichhabra commented on _data/blogs.yml
> +
url: https://fossasiasblog.wordpress.com
title FOSS ASIA AND ME 
img: IMG_4670
author_name: Kaushiki Chhabra

2018-01-03 00:20 UTC, 0x48piraj requested changes
Please close this PR, and make a new one!
Or,
Remove conflicts, rebase, squash commits :+1:

2018-01-03 18:50 UTC, akshatnitd reviewed
@kaushikichhabra I would suggest you to open up a new PR for this! :)

2018-01-04 07:30 UTC, nikit19 reviewed
Please open a new pull request and send it from your forked repository

2018-01-04 07:30 UTC, closed without merging