Fixes #755 : Optimized/Compressed some images
fossasia/gci17.fossasia.org pull request #758
Opened 2018-01-02 20:48 UTC by 0x48piraj

# Fixes #755 

- [x] Read and understood (see CONTRIBUTING.md)
- [x] Included a Preview link and screenshot showning after and before the changes.
- [x] Images are `240 x 240` [w x h].
- [x] Included a description of change below.
- [x] Squashed the commits.

# Changes done in this Pull Request

- _**Changes can't be previewed as they are of back-end/optimization**_ 
- Fixes #755 

> _Reference : https://github.com/fossasia/gci17.fossasia.org/pull/756_

Ping @harshit98 @ParthS007

2018-01-02 21:35 UTC, YashKumarVerma approved these changes

2018-01-02 21:47 UTC, sayak119 approved these changes

2018-01-03 08:27 UTC, vaibhavsingh97 requested changes
can you tell me that what was the size of image before and after your fix?

2018-01-03 10:37 UTC, 0x48piraj commented
**_`fossasia-light.png` - 8.47kb to 8.16 kb_**
**_`flask_0x48piraj.png` - 32.5 to 15.2 kb_**
**_`emberjs_0x48piraj.png` - 67.8kb to 50.7kb_**
**_`AAK_logo.png` - 42-3 kb to 27.1kb_**

@vaibhavsingh97 :+1:

2018-01-03 13:45 UTC, harshit98 approved these changes

2018-01-03 13:45 UTC, merged

2018-01-03 14:48 UTC, vaibhavsingh97 commented
Good job @0x48piraj 💯