Update blogs.yml
fossasia/gci17.fossasia.org pull request #789
Opened 2018-01-04 11:19 UTC by MomtahinaKarim

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-04 11:38 UTC, nikit19 requested changes
Please make these changes

2018-01-04 11:38 UTC, nikit19 commented on _data/blogs.yml
> -#   author_name: Name of the author of the blog (most likely you)
Please don't delete this

2018-01-04 11:38 UTC, nikit19 commented on _data/blogs.yml
> +  img: Momtahina.png
Please upload this image in the img/blogs folder

2018-01-05 09:24 UTC, ParthS007 commented
closing this as a duplicate of #789

2018-01-05 09:24 UTC, closed without merging