Update .gitignore
fossasia/gci17.fossasia.org pull request #805
Opened 2018-01-06 13:58 UTC by ShivamRai2003

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-06 17:36 UTC, nikit19 reviewed
Please describe in your pull request what you are trying to do

2018-01-06 17:41 UTC, ShivamRai2003 commented
to complete my task i am doing this so how to merge it now

On Sat, Jan 6, 2018 at 11:06 PM, Nikit Bhandari <notifications@github.com>
wrote:

> *@nikit19* commented on this pull request.
>
> Please describe in your pull request what you are trying to do
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/805#pullrequestreview-87080446>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhVfd2LY2vJDAkg86EtgWcZ8Af1icGSpks5tH68EgaJpZM4RVUWq>
> .
>

2018-01-06 17:55 UTC, nikit19 commented
Please go through the README.md 
https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md
to see how to complete your task correctly

2018-01-06 17:59 UTC, ShivamRai2003 commented
please tell me how to merge a pull request please

On Sat, Jan 6, 2018 at 11:25 PM, Nikit Bhandari <notifications@github.com>
wrote:

> Please go through the README.md
> https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md
> to see how to complete your task correctly
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/805#issuecomment-355763658>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhVfd_WMC06GBEB4rZJ8gbL0MMmcB9XCks5tH7ORgaJpZM4RVUWq>
> .
>

2018-01-06 18:05 UTC, ShivamRai2003 commented
please tell

On Sat, Jan 6, 2018 at 11:29 PM, SHIVAM RAI <srai14429467@gmail.com> wrote:

> please tell me how to merge a pull request please
>
> On Sat, Jan 6, 2018 at 11:25 PM, Nikit Bhandari <notifications@github.com>
> wrote:
>
>> Please go through the README.md
>> https://github.com/fossasia/gci17.fossasia.org/blob/gh-pages/README.md
>> to see how to complete your task correctly
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/fossasia/gci17.fossasia.org/pull/805#issuecomment-355763658>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AhVfd_WMC06GBEB4rZJ8gbL0MMmcB9XCks5tH7ORgaJpZM4RVUWq>
>> .
>>
>
>

2018-01-06 18:07 UTC, isuruAb reviewed
Hello @ShivamRai2003 , could you please explain what you tried to do here. you haven't write permissions so you can't merge but maintainers/mentors can do that.

2018-01-06 18:08 UTC, nikit19 commented
You first need to complete your task properly. Then it will get merged.
Please go through the README.md to understand how to do that

2018-01-06 18:09 UTC, ShivamRai2003 commented
only one is left that pull a request and merge it

On Sat, Jan 6, 2018 at 11:38 PM, Nikit Bhandari <notifications@github.com>
wrote:

> You first need to complete your task properly. Then it will get merged.
> Please go through the README.md to understand how to do that
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/gci17.fossasia.org/pull/805#issuecomment-355764546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhVfdyXiOCPmbvXT_oFR7nlwySv7ibExks5tH7algaJpZM4RVUWq>
> .
>

2018-01-07 13:56 UTC, abishekvashok requested changes

2018-01-07 13:56 UTC, abishekvashok commented on .gitignore
> +- name: Shivam rai
Invalid unrequired change.

2018-01-08 01:39 UTC, isuruAb requested changes
don't add your information to the .gitignore file.  Upload correct 240x240 sized one image .

2018-01-08 04:25 UTC, closed without merging