Update blogs.yml
fossasia/gci17.fossasia.org pull request #806
Opened 2018-01-06 14:37 UTC by ShahaamMarzook

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-06 14:59 UTC, 0x48piraj requested changes
Fix Travis errors

2018-01-06 15:09 UTC, ShahaamMarzook commented
Direct me how to update blog in this so that I could finish my task GCI17

2018-01-06 15:11 UTC, ShahaamMarzook reviewed
Is this correct 
Or what should I do to update the blog

2018-01-06 15:19 UTC, abishekvashok requested changes
The image should be 240x240px

2018-01-06 15:19 UTC, abishekvashok commented on _data/blogs.yml
> +  - url: https://workingwithfossasiawordpress.wordpress.com/2018/01/06/participation-in-open-source-community/
No spaces before -

2018-01-06 16:37 UTC, nikit19 requested changes
Please make the above changes and upload the image in the img/blogs folder

2018-01-06 18:36 UTC, isuruAb reviewed
please resolve Travis failure

2018-01-07 07:57 UTC, abishekvashok requested changes
You need to upload the image as well under the name `Blog pic.jpeg` to img/blogs/

2018-01-12 13:28 UTC, ParthS007 reviewed
@ShahaamMarzook Closing this PR due to many conflicts and inactivity.Please read `README.MD` on how to add a blog and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

2018-01-12 13:28 UTC, closed without merging