Merge my Blog and the picture
fossasia/gci17.fossasia.org pull request #807
Opened 2018-01-06 17:40 UTC by ShahaamMarzook

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-06 17:51 UTC, nikit19 requested changes
Looks good! Just resolve the conflict :+1:

2018-01-06 18:08 UTC, isuruAb reviewed
please resolve conflicts.

2018-01-07 07:59 UTC, ShahaamMarzook reviewed
Accpt this So,that my task would be apporved

2018-01-07 08:42 UTC, ShahaamMarzook commented
Accept my pr please

2018-01-07 11:19 UTC, ShahaamMarzook commented
please Merge my pull request

2018-01-07 15:31 UTC, ShahaamMarzook commented
@nikit19 please approve this now ASAP
I'm tring to fiish this take for the past two days, willing to do the other tasks.Please approve this as well as my task  https://codein.withgoogle.com/dashboard/task-instances/5733699029041152/

2018-01-07 16:31 UTC, ShahaamMarzook commented
Mentors,
   Please approve this and merge this , because I'm trying to pass this for the past 02 days.And help me in completing the task ;
 https://codein.withgoogle.com/dashboard/task-instances/5733699029041152/

2018-01-07 16:42 UTC, ShahaamMarzook commented
Mentors,
Please approve this and merge this , because I'm trying to pass this for the past 02 days.And help me in completing the task ;  😄 
https://codein.withgoogle.com/dashboard/task-instances/5733699029041152/?sp-page=2

2018-01-07 16:46 UTC, ShahaamMarzook commented
@nikit19 So,have I merged my blog into the main repository.
😮

2018-01-07 16:54 UTC, nikit19 requested changes
Please make this change

2018-01-07 16:54 UTC, nikit19 commented on _data/blogs.yml
> +  img: Shahaam.jpeg
The image that you uploaded and wrote here don't have the same name.
One ends with jpg and the other with jpeg.
Please make it same

2018-01-07 17:49 UTC, realslimshanky requested changes
Please squash your commits.

2018-01-08 03:34 UTC, ShahaamMarzook commented
I have uploaded the picture in the img/blog As Shahaam.jpg 
Please review my task and accept the pull request as well.   😄 
https://codein.withgoogle.com/dashboard/task-instances/5733699029041152/

With respect,
Shahaam Marzook

2018-01-08 07:11 UTC, nikit19 commented
But you wrote 'Shahaam.jpeg' in blogs.yml
The name is different,please make it same both the places

2018-01-08 14:28 UTC, harshit98 approved these changes
Good work!

2018-01-08 14:28 UTC, merged