Shivam rai2003 patch 2
fossasia/gci17.fossasia.org pull request #824
Opened 2018-01-07 11:35 UTC by ShivamRai2003

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-07 12:12 UTC, nikit19 requested changes
Please make this change and make sure that the dimensions of your image is 240 x 240 pixels

2018-01-07 12:12 UTC, nikit19 commented on .gitignore
> +#   twitter: Shivam Rai
Please don't write anything here

2018-01-07 13:58 UTC, codedsun requested changes
Image is not of appropriate size.

2018-01-07 18:31 UTC, ShivamRai2003 commented
now what is the problem

2018-01-08 01:41 UTC, isuruAb requested changes
I saw 3 duplicate PRs from you.please check those and close unwanted PRs. please don't add your details to the.gitignore file.

2018-01-08 04:22 UTC, closed without merging