Update blogs.yml
fossasia/gci17.fossasia.org pull request #827
Opened 2018-01-08 08:20 UTC by ShubhamGhanmode

How to upload phot?

2018-01-08 08:25 UTC, nikit19 reviewed
Upload the photo in your forked repository in the img/blogs folder

2018-01-08 09:42 UTC, anshumanv commented on _data/blogs.yml
> +  img: syg.jpg
Please upload an image with this name.

2018-01-08 13:20 UTC, codedsun requested changes
Add your image :)

2018-01-08 17:11 UTC, 0x48piraj requested changes
Indent too

2018-01-09 01:57 UTC, isuruAb reviewed
please resolve conflicts

2018-01-12 13:31 UTC, ParthS007 reviewed
@ShubhamGhanmode  Closing this PR due to many conflicts and inactivity.Please read `README.MD` on how to add a blog and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

2018-01-12 13:31 UTC, closed without merging