I filled in my particulars and included my image already
fossasia/gci17.fossasia.org pull request #831
Opened 2018-01-08 13:13 UTC by dhs17y1jLimYuWei

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-08 13:25 UTC, codedsun commented
@dhs17y1jLimYuWei Please squash your commits!

2018-01-08 13:30 UTC, nikit19 requested changes
Looks good ! Just make sure that the dimensions of your image is 240 x 240 pixels

2018-01-08 13:34 UTC, nikit19 commented on _data/students.yml
> +  twitter: @MrNobodi123
There is no @ in your username if I am right?

2018-01-08 17:09 UTC, 0x48piraj requested changes
UPDATE your PR

2018-01-12 13:41 UTC, ParthS007 reviewed
@dhs17y1jLimYuWei Please resize your image to `240*240`  and update your PR 👍

2018-01-13 05:04 UTC, anshumanv reviewed
Upload image of 240x240 and resolve conflicts

2018-01-13 05:39 UTC, abishekvashok requested changes
Pls resize your image to `240x240px`

2018-01-13 06:32 UTC, harshit98 commented
Good job! You're almost there to complete this pull request. Make your image dimensions 240 x 240.

2018-01-13 12:31 UTC, isuruAb reviewed
please resolve conflicts  and check the travis failure

2018-01-16 19:15 UTC, ParthS007 reviewed
@dhs17y1jLimYuWei  Closing this PR due to many conflicts and inactivity.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

2018-01-16 19:15 UTC, closed without merging