Added my photo to student section
fossasia/gci17.fossasia.org pull request #834
Opened 2018-01-08 14:27 UTC by shreyankt99

Uodated student.yml and added my img
https://shreyankt99.github.io/gci17.fossasiashreynkt.org/.

2018-01-08 14:56 UTC, nikit19 requested changes
Looks good just make this change

2018-01-08 14:56 UTC, nikit19 commented on _data/students.yml
> -
Don't delete somebody's code. You can write after them

2018-01-08 17:08 UTC, 0x48piraj requested changes
Squash your commits

2018-01-09 17:43 UTC, realslimshanky requested changes
Follow @nikit19 's review, resolve conflicts and squash all your commits.

2018-01-10 09:06 UTC, isuruAb reviewed
please squash your commits and resolve conflicts

2018-01-12 13:37 UTC, ParthS007 reviewed
@shreyankt99 Closing this PR due to many conflicts and inactivity.Please read `README.MD` on how to add a student and make a PR.Please ask on FOSSASIA Gitter channel if you face any difficulty 👍

2018-01-12 13:38 UTC, closed without merging