Add my blog
fossasia/gci17.fossasia.org pull request #839
Opened 2018-01-08 22:39 UTC by ShubhamGhanmode

Pls add my blog.

2018-01-09 01:55 UTC, isuruAb reviewed
please squash your commits and resolve conflicts

2018-01-09 06:02 UTC, nikit19 requested changes
Make sure that the dimensions of your image is 240 x 240 pixels

2018-01-09 06:02 UTC, nikit19 commented on _data/blogs.yml
> +  - url: https://shubham970121859.wordpress.com/
Please remove the space before ' - '

2018-01-09 18:25 UTC, 0x48piraj requested changes
This branch has conflicts that must be resolved

2018-01-11 05:47 UTC, anshumanv requested changes
Resolve conflicts, upload only one rightly sized image.

2018-01-13 06:31 UTC, harshit98 commented
Closing the PR due to inactivity.

2018-01-13 06:31 UTC, closed without merging