Added a Blog
fossasia/gci17.fossasia.org pull request #854
Opened 2018-01-09 16:25 UTC by naveentherocker

Added a Blog to the Blog Section

2018-01-09 16:29 UTC, nikit19 reviewed
Please provide a preview link

2018-01-09 16:42 UTC, naveentherocker commented
@nikit19 This is a Patch.

2018-01-09 17:01 UTC, anshumanv commented on _data/blogs.yml
> +  img: 7.jpg
Please use a different image.

2018-01-09 18:22 UTC, 0x48piraj requested changes
Do the required changes

2018-01-12 13:42 UTC, ParthS007 requested changes
@naveentherocker Please do the suggested changes and update your PR 👍

2018-01-12 13:47 UTC, closed without merging