UPDATE MENTOR.YML
fossasia/gci17.fossasia.org pull request #858
Opened 2018-01-09 18:43 UTC by ShivamRai2003

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-09 18:56 UTC, ShivamRai2003 commented
MENTORS PLEASE REVIEWE IT AND MERGE IT PLZZ

2018-01-09 19:04 UTC, nikit19 requested changes
Please make this change

2018-01-09 19:04 UTC, nikit19 commented on _data/mentors.yml
> +  github: Sean McGregor
This github account doesn't exist. Probably there is no space

2018-01-09 19:18 UTC, ShivamRai2003 commented
please see this one it is correct

2018-01-10 09:00 UTC, isuruAb reviewed
please squash your commits

2018-01-10 14:06 UTC, closed without merging