Radhika
fossasia/gci17.fossasia.org pull request #931
Opened 2018-01-15 15:39 UTC by RadhikaAgarwal

Please read and understand everything below
**Do not delete any text other than where you are instructed.**

**Students: If one of them is applicable to you. Please check it.**

Check by changing each `[ ]` to `[x]` Please take note of the whitespace as it matters.

- [ ] Read and understood (see CONTRIBUTING.md)
- [ ] Included a Preview link and screenshot showning after and before the changes.
- [ ] Images are `240 x 240` [w x h].
- [ ] Included a description of change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request

- If your change will be reflected on the website, please provide a **Test-Link** (**Hint : `gh-pages`**)
- Fixes`#<Issue no.>`

2018-01-15 16:05 UTC, nikit19 requested changes
Please make sure that the dimensions of the image is 240 x 240 pixels.
And please add your photo and details in correct files ie in the students.yml and image should be inside img/students folder

2018-01-15 16:05 UTC, nikit19 commented on Radhika
> +  image: https://github.com/RadhikaAgarwal/gci17.fossasia.org/commit/388bc55f78bf64d68bcb7ac1187c308dc332df6e
You have to write the name of the image here

2018-01-16 07:41 UTC, anshumanv commented on Radhika
> +  image: https://github.com/RadhikaAgarwal/gci17.fossasia.org/commit/388bc55f78bf64d68bcb7ac1187c308dc332df6e
Please change it to image's file name.

2018-01-16 17:20 UTC, NaviRocker requested changes
Please Make sure to finish this Soon.

2018-01-16 19:18 UTC, ParthS007 requested changes
@RadhikaAgarwal  Please do the suggested changes 👍

2018-01-18 07:03 UTC, 0x48piraj requested changes
Status ?

2018-02-01 20:33 UTC, mariobehling commented
Closing due to inactivity.

2018-02-01 20:33 UTC, closed without merging